---
- name: Install Snap
  include_role:
    name: don_rumata.ansible_role_install_snap

# Install "foo" and "bar" snap
# Install a snap with classic confinement
- name: Install SSHoot
  become: true
  command: snap install --classic sshoot
