---
#? ansible-galaxy install -r requirements.yml
roles:
  - name: don_rumata.ansible_role_install_snap
    src: https://github.com/don-rumata/ansible-role-install-snap

  - name: gantsign.minikube
    src: galaxy

  - name: danielrolls.nix
    src: galaxy

  - name: dotstrap.fzf
    src: galaxy

  - name: gantsign.oh-my-zsh
    src: galaxy

  - name: geerlingguy.docker
    src: galaxy

  - name: geerlingguy.pip
    src: galaxy

collections:
  - name: bec.shell
