---
docker_users:
  - fabrice #FIXME: move this to higher level of the repo

docker_install_compose: true
docker_compose_version: "1.29.2" #FIXME: Ubuntu should have latter...
docker_compose_arch: "{{ ansible_architecture }}"
docker_compose_path: /usr/local/bin/docker-compose
