- hosts: local
  tasks:
          - block:
                    - include_role:
                              name: SYSTEM
            name: System preparation
            tags:
                    - wsl
                    - sys

          - block:
                    - include_role:
                              name: DOT
            name: Dot file creations
            tags:
                    - wsl
                    - dot

          - block:
                    - include_role:
                              name: APT
            name: APT package management tasks
            tags:
                    - wsl
                    - apt

          - block:
                    - include_role:
                              name: BREW
            name: BREW package management tasks
            tags:
                    - wsl
                    - brew

          - block:
                    - include_role:
                              name: WSL
            name: WSL2 configuration tasks
            tags:
                    - wsl

          - block:
                    - include_role:
                              name: SYSTEM
            name: Generic sytem configuration tasks
            tags:
                    - wsl
                    - sys

          - block:
                    - include_role:
                              name: BASH
            name: Bash shell configuration tasks
            tags:
                    - wsl
                    - bash

          - become: true
            become_method: sudo
            block:
                    - include_role:
                              name: DOCKER
            name: Docker engine configuration
            tags:
                    - wsl
                    - doc

          - block:
                    - include_role:
                              name: GIT
            name: Git client configuration tasks
            tags:
                    - wsl
                    - git

          - become: true
            become_method: sudo
            block:
                    - include_role:
                              name: K8S
            name: Install Minikube / K8s
            tags:
                    - wsl
                    - k8s

          - block:
                    - include_role:
                              name: SNAP
            name: SnapD and packages
            tags:
                    - wsl
                    - snap

          - block:
                    - include_role:
                              name: SSH
            name: SSH client / server configuration
            tags:
                    - wsl
                    - ssh

          - block:
                    - include_role:
                              name: SSHOOT
            name: Configure SHOOT tunneling - https://github.com/albertodonato/sshoot
            tags:
                    - wsl
                    - sporting
                    - sshoot

          - block:
                    - include_role:
                              name: SPORTING
            name: Configurations specific to Sporting Solutions
            tags:
                    - wsl
                    - sporting

          - block:
                    - include_role:
                              name: ZSH
            name: Shell config
            tags:
                    - wsl
                    - zsh

          - block:
                    - include_role:
                              name: NIX
            name: Add NIX package manager
            tags:
                    - wsl
                    - nix
